---
title: "02_tables"
# output: html_document
---

# Environment

```{r}
library(dplyr)
library(magrittr)
library(tableone)
library(kableExtra)
library(gtsummary)
library(knitr)
library(flextable)
library(tibble)
library(officer)
```

# Load File

```{r}
final_dataset_eICU <- readRDS('C:/Users/se_al/Documents/GitHub/mimiciv-mec-vent/data/eICU/final_dataset_eICU.rds')
```

# Statistics
```{r}
# Print dfSummary
stview(dfSummary(final_dataset_eICU)) 

# Define the list of continuous variables that are not normally distributed
nonnormal_variables <- c('age', 'hospital_stay_days', 'icu_stay_days', 'consecutive_vm_days', 'aps', 'charlson') 

# Testing normality with Kolmogorov-Smirnov test
# A low p-value (usually lower than 0.05) suggests that the variable does not follow a normal distribution
for (col in nonnormal_variables) {
  test_result <- ks.test(final_dataset_eICU[[col]], "pnorm", mean(final_dataset_eICU[[col]]), sd(final_dataset_eICU[[col]]))
  print(paste("Variable:", col))
  print(test_result)
}
```

# Define functions
```{r}
# List of variables and labels for Table1 
labels_list <- list(
  age = 'Age (years)',
  sex = 'Sex',
  hospital_stay_days = 'Hospital stay (days)',
  icu_stay_days = 'ICU stay (days)',
  inhospital_death = 'Hospital Mortality',
  inicu_death = 'ICU Mortality',
  death_30days = '30-day Mortality',
  death_year = '1-year Mortality',
  tbi_anyseq = 'TBI', 
  trauma_type_anyseq = 'Trauma-related cohort',
  consecutive_vm_days = 'Consecutive days with ≥6h IMV',
  mv_consecutive_14days = '≥14 consecutive days of IMV',
  mv_96traq = '96h of IMV + Traq',
  prolonged_mec_vent = 'PMV',
  aps = 'APS score',
  charlson = 'Charlson score'
)

# Function to detect categorical variables
detect_categorical <- function(vars_in_table1, table1_dataset) {
  cat_variables <- c()
  cont <- 1
  
  for (i in 1:length(vars_in_table1)) {
    if (n_distinct(table1_dataset[[vars_in_table1[i]]]) <= 10) {
      print(i)
      print(vars_in_table1[i])
      print(names(table1_dataset[vars_in_table1[i]]))
      cat_variables[cont] <- names(table1_dataset[vars_in_table1[i]])
      cont <- cont + 1
    }
  }
  
  return(cat_variables)
}

# Function to assign labels to variable names
assign_labels <- function(vars_in_table1, table1_dataset, labels_list) {
  for (var in names(labels_list)) {
    if (var %in% vars_in_table1) {
      label(table1_dataset[[var]]) <- labels_list[[var]]
    }
  }
  return(table1_dataset)
}

## Define the root directory
root_dir <- "C:/Users/se_al/Documents/GitHub/mimiciv-mec-vent"

# Function to create and export a docx table using flextable package
create_flextable <- function(table1, values, colwidths, title, save_name) {
  
  # Convert the table to a data frame and adjust columns
  table_df <- as.data.frame(table1) %>%
    rownames_to_column(var = "Variable") %>%
    select(-("test"))  # Removing the 'test' column
  
  # Set default font size for the flextable
  set_flextable_defaults(font.size = 10)
  
  # Create a flextable and format the table
  table_doc <- flextable(table_df) %>%
    add_header_row(
      values = values,   # Custom header values
      colwidths = colwidths  # Custom column widths
    ) %>%
    set_caption(caption = title) %>%
    set_table_properties(layout = "autofit") %>%
    align(align = "left", part = "body", j = 1) %>%  # Aligns first column to the left
    align(align = "center", part = "body", j = 2:ncol(table_df))  # Aligns rest to center
  
  # Export the table to a .docx file
  read_docx() %>%
    body_add_flextable(value = table_doc) %>%
    print(target = file.path(root_dir, "data/eICU/tables", paste0(save_name, ".docx")))  # Save the file with custom name
}
```

# Table one: Traumatic Brain Injury

```{r}
# Lists the variables we are going to be including in table1 (except for the stratification variable)
vars_in_table1<-c('age', 'sex', 'hospital_stay_days', 'icu_stay_days', 'discharge_location', 'inhospital_death', 'inicu_death', 'death_30days', 'anytrauma_seq1','anytrauma_anyseq', 'trauma_type_seq1', 'trauma_type_anyseq', 'consecutive_vm_days', 'mv_consecutive_7days', 'mv_consecutive_14days', 'mv_consecutive_21days', 'total_vm_days', 'mv_total_7days', 'mv_total_14days', 'mv_total_21days', 'mv_96traq', 'prolonged_mec_vent', 'exit_with_mv', 'aps', 'apache', 'charlson', 'gcs') 

# Creates a dataset with only selected variables using our original dataset and generates an empty list for storing categorical variables
stratifyby <- c("tbi_anyseq")
table1_dataset <- final_dataset_eICU[,c(vars_in_table1, stratifyby)]
cat_variables <- rep(NA, length(vars_in_table1))

# Assign labels to variable names
table1_dataset <- assign_labels(vars_in_table1, table1_dataset, labels_list)

# Detects whether a variable is categorical or not and eliminates null values
cat_variables <- detect_categorical(vars_in_table1, table1_dataset)
cat_variables<-cat_variables[!is.na(cat_variables)]

# Creates table one
table1_tbi<-print(CreateTableOne(vars = vars_in_table1, strata = stratifyby, factorVars = cat_variables, data = table1_dataset, addOverall=T),varLabels = T)

# Run this in console for html output, the code below uses kableExtra::
 starification_cats<-n_distinct(table1_dataset[,stratifyby])
 
# For console
 table1_tbi %>%
   kbl(caption = "Table 1 of base model: Traumatic Brain Injury. eICU Database" , align = "c") %>%
   kable_classic_2(full_width = F, html_font = "Cambria") %>%
   add_header_above(c("", "", "No", "Yes", "", ""))

# # Export kable 
#   table1_tbi %>%
#    kbl(caption = "Table 1 of base model: Traumatic Brain Injury. eICU Database" , align = "c") %>%
#    kable_classic_2(full_width = F, html_font = "Cambria") %>%
#    add_header_above(c("", "", "No", "Yes", "", "")) %>%
#    save_kable("C:/Users/se_al/Documents/GitHub/mimiciv-mec-vent/figures/eICU/Table1/table1_tbi_eicu.jpg", zoom = 10)

```

# Table one: Hospital Mortality 

```{r}
# Lists the variables we are going to be including in table1 (except for the stratification variable)
vars_in_table1<-c('age', 'sex', 'hospital_stay_days', 'icu_stay_days', 'inicu_death', 'death_30days', 'tbi_anyseq', 'trauma_type_anyseq', 'consecutive_vm_days',  'mv_consecutive_14days', 'mv_96traq', 'prolonged_mec_vent', 'aps', 'charlson') 

# Creates a dataset with only selected variables using our original dataset and generates an empty list for storing categorical variables
stratifyby <- "inhospital_death"
table1_dataset <- final_dataset_eICU[,c(vars_in_table1, stratifyby)]
table1_dataset$inhospital_death <- factor(table1_dataset$inhospital_death, labels = c("No", "Yes"))
cat_variables <- rep(NA, length(vars_in_table1))

# Assign labels to variable names
table1_dataset <- assign_labels(vars_in_table1, table1_dataset, labels_list)

# Detects whether a variable is categorical or not and eliminates null values
cat_variables <- detect_categorical(vars_in_table1, table1_dataset)
cat_variables<-cat_variables[!is.na(cat_variables)]

# Creates table one
table1 <- print(
  CreateTableOne(
    vars = vars_in_table1,
    strata = stratifyby,
    factorVars = cat_variables,
    data = table1_dataset,
    addOverall = T
  ),
  nonnormal = nonnormal_variables,
  formatOptions = list(big.mark = ","),
  varLabels = T
)

# Run this in console for html output, the code below uses kableExtra::
 starification_cats<-n_distinct(table1_dataset[,stratifyby])
 
# For console
 table1 %>%
   kbl(caption = "Table 1 of base model: Hospital Mortality. eICU Database" , align = "c") %>%
   kable_classic_2(full_width = F, html_font = "Cambria") %>%
   add_header_above(c("", "", "Hospital Mortality"=2, "", ""))
 
# Export table in docx
create_flextable(
  table1 = table1,
  values = c("", "", "Hospital Mortality", ""),
  colwidths = c(1, 1, 2, 1),
  title = "Baseline characteristics of eICU study population stratified by Hospital Mortality",
  save_name = "table1_hospdeath_eICU"
)
 
# # Export kable
#  table1 %>%
#    kbl(caption = "Table 1 of base model: Hospital Mortality eICU Database" , align = "c") %>%
#    kable_classic_2(full_width = F, html_font = "Cambria") %>%
#    add_header_above(c("", "", "No", "Yes", "", "")) %>%
#    save_kable("C:/Users/se_al/Documents/GitHub/mimiciv-mec-vent/figures/eICU/Table1/table1_hospdeath_eicu.jpg", zoom = 10)
 
```

# Table one: Prolonged Mecanical Ventilation

```{r}
# Lists the variables we are going to be including in table1 (except for the stratification variable)
vars_in_table1<-c('age', 'sex', 'hospital_stay_days', 'icu_stay_days', 'inhospital_death', 'inicu_death', 'death_30days', 'tbi_anyseq', 'trauma_type_anyseq', 'consecutive_vm_days',  'mv_consecutive_14days', 'mv_96traq', 'aps', 'charlson') 

# Creates a dataset with only selected variables using our original dataset and generates an empty list for storing categorical variables
stratifyby <- "prolonged_mec_vent"
table1_dataset <- final_dataset_eICU[,c(vars_in_table1, stratifyby)]
table1_dataset$prolonged_mec_vent <- factor(table1_dataset$prolonged_mec_vent, labels = c("No", "Yes"))
cat_variables <- rep(NA, length(vars_in_table1))

# Assign labels to variable names
table1_dataset <- assign_labels(vars_in_table1, table1_dataset, labels_list)

# Detects whether a variable is categorical or not and eliminates null values
cat_variables <- detect_categorical(vars_in_table1, table1_dataset)
cat_variables<-cat_variables[!is.na(cat_variables)]

# Creates table one
table1 <- print(
  CreateTableOne(
    vars = vars_in_table1,
    strata = stratifyby,
    factorVars = cat_variables,
    data = table1_dataset,
    addOverall = T
  ),
  nonnormal = nonnormal_variables,
  formatOptions = list(big.mark = ","),
  varLabels = T
)

# Run this in console for html output, the code below uses kableExtra::
 starification_cats<-n_distinct(table1_dataset[,stratifyby])
 
# For console
 table1 %>%
   kbl(caption = "Table 1 of base model: Prolonged Mechanical Ventilation. eICU Database" , align = "c") %>%
   kable_classic_2(full_width = F, html_font = "Cambria") %>%
   add_header_above(c("", "", "PMV"=2, "", ""))
 
# Export table in docx
create_flextable(
  table1 = table1,
  values = c("", "", "PMV", ""),
  colwidths = c(1, 1, 2, 1),
  title = "Baseline characteristics of eICU study population stratified by PMV",
  save_name = "table1_PMV_eICU"
)
 
# #Export kable
#  table1 %>%  
#    kbl(caption = "Table 1 of base model: Prolonged Mechanical Ventilation. eICU Database" , align = "c") %>%
#    kable_classic_2(full_width = F, html_font = "Cambria") %>%
#    add_header_above(c("", "", "No", "Yes", "", "")) %>% 
#    save_kable("C:/Users/se_al/Documents/GitHub/mimiciv-mec-vent/figures/eICU/Table1/table1_pmv_eicu.jpg", zoom = 10)
```


# Table one: 4 Trauma types

```{r}
# Lists the variables we are going to be including in table1 (except for the stratification variable)
vars_in_table1<-c('age', 'sex', 'hospital_stay_days', 'icu_stay_days', 'inhospital_death', 'inicu_death', 'death_30days', 'tbi_anyseq', 'consecutive_vm_days',  'mv_consecutive_14days', 'mv_96traq', 'prolonged_mec_vent', 'aps', 'charlson')

# Creates a dataset with only selected variables using our original dataset and generates an empty list for storing categorical variables
stratifyby <- "trauma_type_anyseq"
table1_dataset <- final_dataset_eICU[,c(vars_in_table1, stratifyby)]
cat_variables <- rep(NA, length(vars_in_table1))

# Assign labels to variable names
table1_dataset <- assign_labels(vars_in_table1, table1_dataset, labels_list)

# Detects whether a variable is categorical or not and eliminates null values
cat_variables <- detect_categorical(vars_in_table1, table1_dataset)
cat_variables<-cat_variables[!is.na(cat_variables)]

# Creates table one
table1 <- print(
  CreateTableOne(
    vars = vars_in_table1,
    strata = stratifyby,
    factorVars = cat_variables,
    data = table1_dataset,
    addOverall = T
  ),
  nonnormal = nonnormal_variables,
  formatOptions = list(big.mark = ","),
  varLabels = T
)

# Run this in console for html output, the code below uses kableExtra::
 starification_cats<-n_distinct(table1_dataset[,stratifyby])
 
# For console
 table1 %>%
   kbl(caption = "Table 1 of base model: Trauma Types. eICU Database" ,     align = "c") %>%
   kable_classic_2(full_width = F, html_font = "Cambria") %>%
   add_header_above(c("", "", "Trauma-related cohorts"=4, " ", " "))
 
# Export table in docx
create_flextable(
  table1 = table1,
  values = c("", "", "Trauma-related cohorts", ""),
  colwidths = c(1, 1, 4, 1),
  title = "Baseline characteristics of eICU study population stratified by Trauma-related diagnoses",
  save_name = "table1_trauma_eICU"
)
 
# # Export kable
#  table1 %>%
#    kbl(caption = "Table 1 of base model: Table 1 of base model: Trauma types. eICU Database" ,     align = "c") %>%
#    kable_classic_2(full_width = F, html_font = "Cambria") %>%
#    add_header_above(c("", "", "No TBI and no Mec Vent", "TBI without Mec Vent", "No TBI and Mec Vent",     "TBI + Mec-Vent ", " ", " ")) %>%
#    save_kable("C:/Users/se_al/Documents/GitHub/mimiciv-mec-vent/figures/eICU/Table1/table1_tbi_and_pmv_eicu.jpg", zoom = 10)
```

# Table one: severe TBI and hospital mortality

```{r}
# Lists the variables we are going to be including in table1 (except for the stratification variable)
vars_in_table1<-c('age', 'sex', 'hospital_stay_days', 'icu_stay_days', 'inicu_death', 'death_30days', 'consecutive_vm_days',  'mv_consecutive_14days', 'mv_96traq', 'prolonged_mec_vent', 'aps', 'charlson') 

# Creates a dataset with only selected variables using our original dataset and generates an empty list for storing categorical variables
stratifyby <- c("inhospital_death")
table1_dataset <- final_dataset_eICU[final_dataset_eICU$trauma_type_anyseq=="severe TBI",
                                        c(vars_in_table1, stratifyby)]
table1_dataset$inhospital_death <- factor(table1_dataset$inhospital_death, labels = c("Alive", "Expired"))
cat_variables <- rep(NA, length(vars_in_table1))

# Extract 90th percentile of severe TBI expired cohort patients
filtered_dataset <- table1_dataset[table1_dataset$inhospital_death == "Expired", ]
percentile_90 <- quantile(filtered_dataset$icu_stay_days, 0.90, na.rm = TRUE)
percentile_90

# Assign labels to variable names
table1_dataset <- assign_labels(vars_in_table1, table1_dataset, labels_list)

# Detects whether a variable is categorical or not and eliminates null values
cat_variables <- detect_categorical(vars_in_table1, table1_dataset)
cat_variables<-cat_variables[!is.na(cat_variables)]

# Creates table one
table1 <- print(
  CreateTableOne(
    vars = vars_in_table1,
    strata = stratifyby,
    factorVars = cat_variables,
    data = table1_dataset,
    addOverall = T
  ),
  nonnormal = nonnormal_variables,
  formatOptions = list(big.mark = ","),
  varLabels = T
)

# Run this in console for html output, the code below uses kableExtra::
 starification_cats<-n_distinct(table1_dataset[,stratifyby])
 
# For console
 table1 %>%
   kbl(caption = "Table 1 of base model:  severe TBI patient cohort and Hospital Mortality. eICU Database" ,     align = "c") %>%
   kable_classic_2(full_width = F, html_font = "Cambria") %>%
   add_header_above(c("", "", "Hospital Mortality"=2, "", ""))
 
# # Export kable
#  table1 %>%
#    kbl(caption = "Table 1 of base model: non-TBI Trauma VS Prolonged Mechanical Ventilation. eICU Database" ,     align = "c") %>%
#    kable_classic_2(full_width = F, html_font = "Cambria") %>%
#    add_header_above(c("", "", "Non-TBI Trauma"=2, "", "")) %>%
#    save_kable("C:/Users/se_al/Documents/GitHub/mimiciv-mec-vent/figures/eICU/Table1/table1_severetbi&hospdeath_eICU.jpg", zoom = 10)
```

# Table one: TBI and PMV

```{r}
# Lists the variables we are going to be including in table1 (except for the stratification variable)
vars_in_table1<-c('age', 'sex', 'hospital_stay_days', 'icu_stay_days', 'discharge_location', 'inhospital_death', 'inicu_death', 'death_30days', 'tbi_seq1', 'tbi_anyseq', 'anytrauma_seq1','anytrauma_anyseq', 'trauma_type_seq1', 'trauma_type_anyseq', 'consecutive_vm_days', 'mv_consecutive_7days', 'mv_consecutive_14days', 'mv_consecutive_21days', 'total_vm_days', 'mv_total_7days', 'mv_total_14days', 'mv_total_21days', 'mv_96traq', 'prolonged_mec_vent', 'exit_with_mv', 'aps', 'apache', 'charlson', 'gcs') 

# Creates a dataset with only selected variables using our original dataset and generates an empty list for storing categorical variables
table1_dataset <- final_dataset_eICU[,vars_in_table1]
cat_variables <- rep(NA, length(vars_in_table1))

# Detects whether a variable is categorical or not
cont <- 1
for (i in 1:length(vars_in_table1) ) {
  if ( n_distinct(table1_dataset[vars_in_table1[i] ])<=10 ) {
    print(i)
    print(vars_in_table1[i])
    print(names(table1_dataset[vars_in_table1[i]]))
    cat_variables[cont]<-names(table1_dataset[vars_in_table1[i]])
    cont<-cont+1
  }
}

# Establishes the stratification variables and eliminates null values from 'cat_variables'
stratifyby <- c("tbi_anyseq", "prolonged_mec_vent")
cat_variables<-cat_variables[!is.na(cat_variables)]

# Creates table one

table1_tbi_and_pmv<-print(CreateTableOne(vars = vars_in_table1, strata = stratifyby, factorVars = cat_variables, data = table1_dataset, addOverall=T),varLabels = T)

# Run this in console for html output, the code below uses kableExtra::
 starification_cats<-n_distinct(table1_dataset[,stratifyby])
 
# For console
 table1_tbi_and_pmv %>%
   kbl(caption = "Table 1 of base model: Traumatic Brain Injury VS Prolonged Mechanical Ventilation. eICU Database" ,     align = "c") %>%
   kable_classic_2(full_width = F, html_font = "Cambria") %>%
   add_header_above(c("", "", "No TBI and no Mec Vent", "TBI without Mec Vent", "No TBI and Mec Vent",     "TBI + Mec-Vent ", " ", " "))
 
# # Export kable
#  table1_tbi_and_pmv %>%
#    kbl(caption = "Table 1 of base model: Traumatic Brain Injury VS Prolonged Mechanical Ventilation. eICU Database" ,     align = "c") %>%
#    kable_classic_2(full_width = F, html_font = "Cambria") %>%
#    add_header_above(c("", "", "No TBI and no Mec Vent", "TBI without Mec Vent", "No TBI and Mec Vent",     "TBI + Mec-Vent ", " ", " ")) %>%
#    save_kable("C:/Users/se_al/Documents/GitHub/mimiciv-mec-vent/figures/eICU/Table1/table1_tbi_and_pmv_eicu.jpg", zoom = 10)
```

# Table one: Subset of TBI and PMV

```{r}
# Subset table with only patients with traumatic bran injury
table1_dataset <- final_dataset_eICU %>% 
  filter(tbi_anyseq==1 & prolonged_mec_vent==1)

# Lists the variables we are going to be including in table1 (except for the stratification variable)
vars_in_table1<-c('age', 'sex', 'hospital_stay_days', 'icu_stay_days', 'inhospital_death', 'inicu_death', 'death_30days', 'tbi_severe_anyseq', 'consecutive_vm_days', 'mv_consecutive_7days', 'mv_consecutive_14days', 'mv_consecutive_21days', 'total_vm_days', 'mv_total_7days', 'mv_total_14days', 'mv_total_21days', 'mv_96traq', 'prolonged_mec_vent', 'aps', 'apache', 'charlson', 'gcs') 

# Creates a dataset with only selected variables using our original dataset and generates an empty list for storing categorical variables
table1_dataset <- table1_dataset[,vars_in_table1] 
cat_variables <- rep(NA, length(vars_in_table1))

# Detects whether a variable is categorical or not
cont <- 1
for (i in 1:length(vars_in_table1) ) {
  if ( n_distinct(table1_dataset[vars_in_table1[i] ])<=10 ) {
    print(i)
    print(vars_in_table1[i])
    print(names(table1_dataset[vars_in_table1[i]]))
    cat_variables[cont]<-names(table1_dataset[vars_in_table1[i]])
    cont<-cont+1
  }
}

# Establishes the stratification variables and eliminates null values from 'cat_variables'
stratifyby <- c("tbi_severe_anyseq")
cat_variables<-cat_variables[!is.na(cat_variables)]

# Creates table one
table1_tbi<-print(CreateTableOne(vars = vars_in_table1, strata = stratifyby, factorVars = cat_variables, data = table1_dataset, addOverall=T),varLabels = T)

# Run this in console for html output, the code below uses kableExtra::
 starification_cats<-n_distinct(table1_dataset[,stratifyby])
 
# For console
 table1_tbi %>%
   kbl(caption = "Table 1 of base model: Subset of Patients with TBI and PMV. eICU Database" , align = "c") %>%
   kable_classic_2(full_width = F, html_font = "Cambria") %>%
   add_header_above(c("", "", "Non-severe TBI", "Severe TBI", "", ""))

# # Export kable 
#   table1_tbi %>%
#    kbl(caption = "Table 1 of base model: Subset of Patients with TBI and PMV. eICU Database" , align = "c") %>%
#    kable_classic_2(full_width = F, html_font = "Cambria") %>%
#    add_header_above(c("", "", "Non-severe TBI", "Severe TBI", "", "")) %>%
#    save_kable("C:/Users/se_al/Documents/GitHub/mimiciv-mec-vent/figures/eICU/Table1/table1_subset_tbi-pmv_eicu.jpg", zoom = 10)

```