---
title: "02_tables"
# output: html_document
---

# Environment

```{r}
library(dplyr)
library(magrittr)
library(tableone)
library(kableExtra)
library(gtsummary)
library(knitr)

```

#Load File

```{r}
final_dataset <- read.csv('C:/Users/se_al/Documents/GitHub/mimic_mec_vent/data/final_dataset.csv')
```

# Table one. Stratified by Traumatic Brain Injury

```{r}
# Lists the variables we are going to be including in table1 (except for the stratification variable)
vars_in_table1<-c('age', 'gender', 'hospital_stay_days', 'icu_stay_days', 'discharge_location', 'inhospital_death', 'inicu_death', 'death_30days', 'death_year', 'tbi_seq_1', 'tbi_any_seq', 'anytrauma_seq_1','anytrauma_any_seq', 'tbi_severe_seq1', 'tbi_nonsevere_seq1', 'trauma_type', 'consecutive_vm_days', 'mv_consecutive_7days', 'mv_consecutive_14days', 'mv_consecutive_21days', 'total_vm_days', 'mv_total_7days', 'mv_total_14days', 'mv_total_21days', 'mv_96traq', 'prolonged_mec_vent', 'apsiii', 'apsiii_prob', 'sapsii', 'sapsii_prob', 'gcs_min', 'gcs_motor', 'gcs_verbal', 'gcs_eyes', 'sofa', 'respiration', 'coagulation', 'liver', 'cardiovascular', 'cns', 'renal') 

# Creates a dataset with only selected variables using our original dataset and generates an empty list for storing categorical variables
table1_dataset <- final_dataset[,vars_in_table1]
cat_variables <- rep(NA, length(vars_in_table1))

# Detects whether a variable is categorical or not
cont <- 1
for (i in 1:length(vars_in_table1) ) {
  if ( n_distinct(table1_dataset[vars_in_table1[i] ])<=10 ) {
    print(i)
    print(vars_in_table1[i])
    print(names(table1_dataset[vars_in_table1[i]]))
    cat_variables[cont]<-names(table1_dataset[vars_in_table1[i]])
    cont<-cont+1
  }
}

# Establishes the stratification variables and eliminates null values from 'cat_variables'
stratifyby <- c("tbi_seq_1")
cat_variables<-cat_variables[!is.na(cat_variables)]

# Creates table one
table1_tbi<-print(CreateTableOne(vars = vars_in_table1, strata = stratifyby, factorVars = cat_variables, data = table1_dataset, addOverall=T),varLabels = T)

# Run this in console for html output, the code below uses kableExtra::
 starification_cats<-n_distinct(table1_dataset[,stratifyby])
 
# For console
 table1_tbi %>%
   kbl(caption = "Table 1 of base model: Traumatic Brain Injury" , align = "c") %>%
   kable_classic_2(full_width = F, html_font = "Cambria") %>%
   add_header_above(c("", "", "No", "Yes", "", ""))

# Export kable 
  table1_tbi %>%
   kbl(caption = "Table 1 of base model: Traumatic Brain Injury" , align = "c") %>%
   kable_classic_2(full_width = F, html_font = "Cambria") %>%
   add_header_above(c("", "", "No", "Yes", "", "")) %>%
   save_kable("C:/Users/se_al/Documents/GitHub/mimic_mec_vent/figures/table1_tbi.jpg", zoom = 10)

```

# Table one. Stratified by Prolonged Mecanical Ventilation

```{r}
# Lists the variables we are going to be including in table1 (except for the stratification variable)
vars_in_table1<-c('age', 'gender', 'hospital_stay_days', 'icu_stay_days', 'discharge_location', 'inhospital_death', 'inicu_death', 'death_30days', 'death_year', 'tbi_seq_1', 'tbi_any_seq', 'anytrauma_seq_1','anytrauma_any_seq', 'tbi_severe_seq1', 'tbi_nonsevere_seq1', 'trauma_type', 'consecutive_vm_days', 'mv_consecutive_7days', 'mv_consecutive_14days', 'mv_consecutive_21days', 'total_vm_days', 'mv_total_7days', 'mv_total_14days', 'mv_total_21days', 'mv_96traq', 'prolonged_mec_vent', 'apsiii', 'apsiii_prob', 'sapsii', 'sapsii_prob', 'gcs_min', 'gcs_motor', 'gcs_verbal', 'gcs_eyes', 'sofa', 'respiration', 'coagulation', 'liver', 'cardiovascular', 'cns', 'renal') 

# Creates a dataset with only selected variables using our original dataset and generates an empty list for storing categorical variables
table1_dataset <- final_dataset[,vars_in_table1]
cat_variables <- rep(NA, length(vars_in_table1))

# Detects whether a variable is categorical or not
cont <- 1
for (i in 1:length(vars_in_table1) ) {
  if ( n_distinct(table1_dataset[vars_in_table1[i] ])<=10 ) {
    print(i)
    print(vars_in_table1[i])
    print(names(table1_dataset[vars_in_table1[i]]))
    cat_variables[cont]<-names(table1_dataset[vars_in_table1[i]])
    cont<-cont+1
  }
}

# Establishes the stratification variables and eliminates null values from 'cat_variables'
stratifyby <- c("prolonged_mec_vent")
cat_variables<-cat_variables[!is.na(cat_variables)]

# Creates table one

table1_pmv<-print(CreateTableOne(vars = vars_in_table1, strata = stratifyby, factorVars = cat_variables, data = table1_dataset, addOverall=T),varLabels = T)

# Run this in console for html output, the code below uses kableExtra::
 starification_cats<-n_distinct(table1_dataset[,stratifyby])
 
# For console
 table1_pmv %>%
   kbl(caption = "Table 1 of base model: Prolonged Mechanical Ventilation" , align = "c") %>%
   kable_classic_2(full_width = F, html_font = "Cambria") %>%
   add_header_above(c("", "", "No", "Yes", "", ""))
 
#Export kable
 table1_pmv %>%  
   kbl(caption = "Table 1 of base model: Prolonged Mechanical Ventilation" , align = "c") %>%
   kable_classic_2(full_width = F, html_font = "Cambria") %>%
   add_header_above(c("", "", "No", "Yes", "", "")) %>% 
   save_kable("C:/Users/se_al/Documents/GitHub/mimic_mec_vent/figures/table1_pmv.jpg", zoom = 10)
```

# Table one. Stratified by Mortality at 30 days

```{r}
# Lists the variables we are going to be including in table1 (except for the stratification variable)
vars_in_table1<-c('age', 'gender', 'hospital_stay_days', 'icu_stay_days', 'discharge_location', 'inhospital_death', 'inicu_death', 'death_30days', 'death_year', 'tbi_seq_1', 'tbi_any_seq', 'anytrauma_seq_1','anytrauma_any_seq', 'tbi_severe_seq1', 'tbi_nonsevere_seq1', 'trauma_type', 'consecutive_vm_days', 'mv_consecutive_7days', 'mv_consecutive_14days', 'mv_consecutive_21days', 'total_vm_days', 'mv_total_7days', 'mv_total_14days', 'mv_total_21days', 'mv_96traq', 'prolonged_mec_vent', 'apsiii', 'apsiii_prob', 'sapsii', 'sapsii_prob', 'gcs_min', 'gcs_motor', 'gcs_verbal', 'gcs_eyes', 'sofa', 'respiration', 'coagulation', 'liver', 'cardiovascular', 'cns', 'renal') 

# Creates a dataset with only selected variables using our original dataset and generates an empty list for storing categorical variables
table1_dataset <- final_dataset[,vars_in_table1]
cat_variables <- rep(NA, length(vars_in_table1))

# Detects whether a variable is categorical or not
cont <- 1
for (i in 1:length(vars_in_table1) ) {
  if ( n_distinct(table1_dataset[vars_in_table1[i] ])<=10 ) {
    print(i)
    print(vars_in_table1[i])
    print(names(table1_dataset[vars_in_table1[i]]))
    cat_variables[cont]<-names(table1_dataset[vars_in_table1[i]])
    cont<-cont+1
  }
}

# Establishes the stratification variables and eliminates null values from 'cat_variables'
stratifyby <- c("death_30days")
cat_variables<-cat_variables[!is.na(cat_variables)]

# Creates table one

table1_death30days<-print(CreateTableOne(vars = vars_in_table1, strata = stratifyby, factorVars = cat_variables, data = table1_dataset, addOverall=T),varLabels = T)

# Run this in console for html output, the code below uses kableExtra::
 starification_cats<-n_distinct(table1_dataset[,stratifyby])
 
# For console
 table1_death30days %>%
   kbl(caption = "Table 1 of base model: Mortality at 30 days" , align = "c") %>%
   kable_classic_2(full_width = F, html_font = "Cambria") %>%
   add_header_above(c("", "", "No", "Yes", "", ""))
 
# Export kable
 table1_death30days %>%
   kbl(caption = "Table 1 of base model: Mortality at 30 days" , align = "c") %>%
   kable_classic_2(full_width = F, html_font = "Cambria") %>%
   add_header_above(c("", "", "No", "Yes", "", "")) %>%
   save_kable("C:/Users/se_al/Documents/GitHub/mimic_mec_vent/figures/table1_death30days.jpg", zoom = 10)
 
```

# Table one. Stratified by Mortality at 1 year

```{r}
# Lists the variables we are going to be including in table1 (except for the stratification variable)
vars_in_table1<-c('age', 'gender', 'hospital_stay_days', 'icu_stay_days', 'discharge_location', 'inhospital_death', 'inicu_death', 'death_30days', 'death_year', 'tbi_seq_1', 'tbi_any_seq', 'anytrauma_seq_1','anytrauma_any_seq', 'tbi_severe_seq1', 'tbi_nonsevere_seq1', 'trauma_type', 'consecutive_vm_days', 'mv_consecutive_7days', 'mv_consecutive_14days', 'mv_consecutive_21days', 'total_vm_days', 'mv_total_7days', 'mv_total_14days', 'mv_total_21days', 'mv_96traq', 'prolonged_mec_vent', 'apsiii', 'apsiii_prob', 'sapsii', 'sapsii_prob', 'gcs_min', 'gcs_motor', 'gcs_verbal', 'gcs_eyes', 'sofa', 'respiration', 'coagulation', 'liver', 'cardiovascular', 'cns', 'renal') 

# Creates a dataset with only selected variables using our original dataset and generates an empty list for storing categorical variables
table1_dataset <- final_dataset[,vars_in_table1]
cat_variables <- rep(NA, length(vars_in_table1))

# Detects whether a variable is categorical or not
cont <- 1
for (i in 1:length(vars_in_table1) ) {
  if ( n_distinct(table1_dataset[vars_in_table1[i] ])<=10 ) {
    print(i)
    print(vars_in_table1[i])
    print(names(table1_dataset[vars_in_table1[i]]))
    cat_variables[cont]<-names(table1_dataset[vars_in_table1[i]])
    cont<-cont+1
  }
}

# Establishes the stratification variables and eliminates null values from 'cat_variables'
stratifyby <- c("death_year")
cat_variables<-cat_variables[!is.na(cat_variables)]

# Creates table one

table1_deathyear<-print(CreateTableOne(vars = vars_in_table1, strata = stratifyby, factorVars = cat_variables, data = table1_dataset, addOverall=T),varLabels = T)

# Run this in console for html output, the code below uses kableExtra::
 starification_cats<-n_distinct(table1_dataset[,stratifyby])
 
# For console
 table1_deathyear %>%
   kbl(caption = "Table 1 of base model: Mortality at 1 year" , align = "c") %>%
   kable_classic_2(full_width = F, html_font = "Cambria") %>%
   add_header_above(c("", "", "No", "Yes", "", ""))
 
# Export kable
 table1_deathyear %>%
   kbl(caption = "Table 1 of base model: Mortality at 1 year" , align = "c") %>%
   kable_classic_2(full_width = F, html_font = "Cambria") %>%
   add_header_above(c("", "", "No", "Yes", "", "")) %>%
   save_kable("C:/Users/se_al/Documents/GitHub/mimic_mec_vent/figures/table1_deathyear.jpg", zoom = 10)
```

# Table one. Stratified by Traumatic Brain Injury and Prolonged Mechanical Ventilation

```{r}
# Lists the variables we are going to be including in table1 (except for the stratification variable)
vars_in_table1<-c('age', 'gender', 'hospital_stay_days', 'icu_stay_days', 'discharge_location', 'inhospital_death', 'inicu_death', 'death_30days', 'death_year', 'tbi_seq_1', 'tbi_any_seq', 'anytrauma_seq_1','anytrauma_any_seq', 'tbi_severe_seq1', 'tbi_nonsevere_seq1', 'trauma_type', 'consecutive_vm_days', 'mv_consecutive_7days', 'mv_consecutive_14days', 'mv_consecutive_21days', 'total_vm_days', 'mv_total_7days', 'mv_total_14days', 'mv_total_21days', 'mv_96traq', 'prolonged_mec_vent', 'apsiii', 'apsiii_prob', 'sapsii', 'sapsii_prob', 'gcs_min', 'gcs_motor', 'gcs_verbal', 'gcs_eyes', 'sofa', 'respiration', 'coagulation', 'liver', 'cardiovascular', 'cns', 'renal') 

# Creates a dataset with only selected variables using our original dataset and generates an empty list for storing categorical variables
table1_dataset <- final_dataset[,vars_in_table1]
cat_variables <- rep(NA, length(vars_in_table1))

# Detects whether a variable is categorical or not
cont <- 1
for (i in 1:length(vars_in_table1) ) {
  if ( n_distinct(table1_dataset[vars_in_table1[i] ])<=10 ) {
    print(i)
    print(vars_in_table1[i])
    print(names(table1_dataset[vars_in_table1[i]]))
    cat_variables[cont]<-names(table1_dataset[vars_in_table1[i]])
    cont<-cont+1
  }
}

# Establishes the stratification variables and eliminates null values from 'cat_variables'
stratifyby <- c("tbi_seq_1", "prolonged_mec_vent")
cat_variables<-cat_variables[!is.na(cat_variables)]

# Creates table one

table1_tbi_and_pmv<-print(CreateTableOne(vars = vars_in_table1, strata = stratifyby, factorVars = cat_variables, data = table1_dataset, addOverall=T),varLabels = T)

# Run this in console for html output, the code below uses kableExtra::
 starification_cats<-n_distinct(table1_dataset[,stratifyby])
 
# For console
 table1_tbi_and_pmv %>%
   kbl(caption = "Table 1 of base model: Traumatic Brain Injury VS Prolonged Mechanical Ventilation" ,     align = "c") %>%
   kable_classic_2(full_width = F, html_font = "Cambria") %>%
   add_header_above(c("", "", "No TBI and no Mec Vent", "TBI without Mec Vent", "No TBI and Mec Vent",     "TBI + Mec-Vent ", " ", " "))
 
# Export kable
 table1_tbi_and_pmv %>%
   kbl(caption = "Table 1 of base model: Traumatic Brain Injury VS Prolonged Mechanical Ventilation" ,     align = "c") %>%
   kable_classic_2(full_width = F, html_font = "Cambria") %>%
   add_header_above(c("", "", "No TBI and no Mec Vent", "TBI without Mec Vent", "No TBI and Mec Vent",     "TBI + Mec-Vent ", " ", " ")) %>%
   save_kable("C:/Users/se_al/Documents/GitHub/mimic_mec_vent/figures/table1_tbi_and_pmv.jpg", zoom = 10)
```
